server:
  port: 8080
spring:
  application:
    name: "Products"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://yenifer:6IdrnXSn7opiGFEo@cluster0.pnidp.mongodb.net/?retryWrites=true&w=majority"
      database: "products"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    groups:
      enabled: true
    path: /swagger-doc/v3/api-docs
  swagger-ui:
    path: /swagger-doc/swagger-ui.html
